version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMMENTS_URL=http://127.0.0.1:5000/comments/
    volumes:
      - ".:/code/"
    ports:
      - "3000:3000"
      - "10000:10000"
    depends_on:
      - reloader
    command: npm run dev

  reloader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/code/"
    command: npm run dev:tailwind