version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/code/"
    ports:
      - "80:3000"
      - "10000:10000"
    command: npm run dev

  reloader:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev:tailwind