version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMMENTS_URL=http://127.0.0.1:5000/comments/
    volumes:
      - ".:/code/"
    ports:
      - "3000:3000"
      - "10000:10000"
    depends_on:
      - hot-reloader
    command: npm run dev

  hot-reloader:
    image: bertini36/tailwind-hot-reloader
    volumes:
      - ".:/code/"
    working_dir: /code/
    tty: true
    command: postcss static/input.css -o static/output.css -w
