version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMMENTS_BASE_URL=http://127.0.0.1:5000/comments/
    volumes:
      - ".:/code/"
    ports:
      - "3000:3000"
      - "10000:10000"
    depends_on:
      - reloader
      - comments_engine
    command: npm run dev

  reloader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/code/"
    command: npm run dev:tailwind

  comments_engine:
    build:
      context: comments_engine/
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: "development"
    volumes:
      - "./comments_engine:/code/"
    ports:
      - "5000:5000"
    command: flask run

  serverless:
    build:
      context: comments_engine/
      dockerfile: ServerlessDockerfile
    env_file:
      - comments_engine/.env
    volumes:
      - "./comments_engine:/code/"
